### PR TITLE
GH200 CI

### PR DESCRIPTION
**Pull request by simonpintarelli**
- Update CI for GH200
- use spack v0.23
- update local recipes to depend on cxx

### CODE REVIEW

**Comment by simonpintarelli** [comment]
cscs-ci run ALPS-DAINT

**Comment by simonpintarelli** [comment]
cscs-ci run GH200

**Comment by simonpintarelli** [comment]
cscs-ci run GH200

**Comment by simonpintarelli** [comment]
cscs-ci run GH200

**Comment by simonpintarelli** [comment]
cscs-ci run GH200

**Comment by simonpintarelli** [comment]
cscs-ci run GH200

**Review by mtaillefumier — APPROVED** [review]
we can merge it

**Pull request merged**
